[project]
name = "duckduckwho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "pre-commit>=4.5.1",
    "pyspark>=4.1.1",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
]
